"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { markScriptsDirty } from "@/lib/list-refresh";

type Draft = { title: string; content: string };

export function InspireButton() {
  const router = useRouter();
  const params = useSearchParams();
  const collectionId = params.get("c");

  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [accepting, setAccepting] = useState(false);
  const [draft, setDraft] = useState<Draft | null>(null);
  const [error, setError] = useState<string | null>(null);
  const dialogRef = useRef<HTMLDivElement | null>(null);

  async function inspire() {
    setBusy(true);
    setError(null);
    setDraft(null);
    try {
      const res = await fetch("/api/scripts/inspire", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ collectionId: collectionId ?? undefined }),
      });
      if (!res.ok) {
        const j = (await res.json().catch(() => null)) as { error?: string } | null;
        setError(j?.error ?? `请求失败 (${res.status})`);
        return;
      }
      const data = (await res.json()) as Draft;
      setDraft(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "请求失败");
    } finally {
      setBusy(false);
    }
  }

  function start() {
    setOpen(true);
    inspire();
  }

  function close() {
    setOpen(false);
    setDraft(null);
    setError(null);
  }

  async function accept() {
    if (!draft) return;
    setAccepting(true);
    const res = await fetch("/api/scripts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        content: draft.content,
        collectionId: collectionId ?? undefined,
      }),
    });
    setAccepting(false);
    if (!res.ok) {
      setError("创建失败");
      return;
    }
    const data = (await res.json()) as { id: string };
    // The POST handler sync-saves content; title is generated by AI in
    // background. Patch the title we already have so we don't waste a second
    // model call.
    if (draft.title) {
      await fetch(`/api/scripts/${data.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: draft.title }),
      }).catch(() => {});
    }
    markScriptsDirty();
    close();
    router.push(`/scripts/${data.id}`);
  }

  // Close on Escape.
  useEffect(() => {
    if (!open) return;
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") close();
    }
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [open]);

  return (
    <>
      <button
        type="button"
        onClick={start}
        aria-label="启发"
        className="inline-flex items-center gap-1 text-sm text-violet-600 dark:text-violet-300 px-2 py-1.5 rounded-md hover:bg-violet-50 dark:hover:bg-violet-950"
      >
        <svg viewBox="0 0 24 24" fill="none" className="w-4 h-4" aria-hidden>
          <path d="M9 18h6M10 21h4M12 3a6 6 0 0 0-3.5 10.9c.5.4.8 1 .9 1.6h5.2c.1-.6.4-1.2.9-1.6A6 6 0 0 0 12 3Z" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
        启发
      </button>

      {open && (
        <div
          className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/40 backdrop-blur-sm"
          onClick={(e) => {
            if (e.target === e.currentTarget) close();
          }}
        >
          <div
            ref={dialogRef}
            className="w-full sm:max-w-lg bg-white dark:bg-neutral-950 rounded-t-2xl sm:rounded-xl border border-neutral-200 dark:border-neutral-800 max-h-[85dvh] flex flex-col"
            style={{ paddingBottom: "env(safe-area-inset-bottom)" }}
          >
            <div className="px-4 pt-4 pb-2 flex items-center justify-between">
              <h2 className="text-base font-semibold">AI 启发</h2>
              <button
                type="button"
                onClick={close}
                aria-label="关闭"
                className="w-8 h-8 inline-flex items-center justify-center rounded-md text-neutral-500 hover:bg-neutral-100 dark:hover:bg-neutral-900"
              >
                <svg viewBox="0 0 24 24" fill="none" className="w-5 h-5" aria-hidden>
                  <path d="M6 6l12 12M18 6L6 18" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" />
                </svg>
              </button>
            </div>

            <div className="flex-1 overflow-y-auto px-4 pb-4">
              {busy && (
                <div className="py-8 text-center text-sm text-neutral-500">
                  正在从你的稿件里找灵感…
                </div>
              )}
              {!busy && error && (
                <div className="py-4 text-sm text-red-600">{error}</div>
              )}
              {!busy && draft && (
                <div className="space-y-2">
                  <div className="text-lg font-semibold">{draft.title || "(无标题)"}</div>
                  <div className="text-sm leading-relaxed whitespace-pre-wrap text-neutral-700 dark:text-neutral-200">
                    {draft.content}
                  </div>
                </div>
              )}
            </div>

            <div className="px-4 py-3 border-t border-neutral-200 dark:border-neutral-800 flex items-center gap-2">
              <button
                type="button"
                onClick={inspire}
                disabled={busy || accepting}
                className="text-sm text-neutral-600 dark:text-neutral-300 px-3 h-9 rounded-md hover:bg-neutral-100 dark:hover:bg-neutral-900 disabled:opacity-40"
              >
                {busy ? "…" : "再启发"}
              </button>
              <div className="flex-1" />
              <button
                type="button"
                onClick={close}
                className="text-sm text-neutral-500 px-3 h-9"
              >
                不采纳
              </button>
              <button
                type="button"
                onClick={accept}
                disabled={!draft || busy || accepting}
                className="text-sm font-medium bg-violet-600 text-white px-4 h-9 rounded-md disabled:opacity-40"
              >
                {accepting ? "…" : "采纳"}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
